spring:
  application:
    name: applicant-management

  # 데이터베이스 설정 (H2 인메모리 데이터베이스)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: koreauniv.kuhas@gmail.com
    password: qdgo jjuo ldny xixs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /

# 로깅 설정
logging:
  level:
    com.example.applicantmanagement: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE